### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by sqleo** [nextui-org/next-pages-template#12]
./components/theme-switch.tsx:46:6
Type error: 'Component' cannot be used as a JSX component.
  Its element type 'Element | Component<any, any, any> | null' is not a valid JSX element.
    Type 'Component<any, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<any, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("E:/work/website-core/node_modules/@types/react-dom/node_modules/@types/react/ts5.0/index").ReactNode'.
            Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
              Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.   

  44 |
  45 |   return (
> 46 |     <Component
     |      ^
  47 |       {...getBaseProps({
  48 |         className: clsx(
  49 |           "px-px transition-opacity hover:opacity-80 cursor-pointer",
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

windows
PS E:\work\website-core> yarn -v
1.22.22
PS E:\work\website-core> node -v
v20.11.1

**Comment by wingkwong** [comment]
Closing - not reproducible. 

<img width="572" alt="image" src="https://github.com/user-attachments/assets/71ae3bdb-236d-415f-90e6-e595cf527ebd">
