### ISSUE TITLE
tempate start with error

### ISSUE THREAD

**Issue by lalalazero** [nextui-org/next-pages-template#5]
Hello~

I just download this tempate and try to run it locally. but I found there're some dependency lack issues.

eg
![image](https://github.com/nextui-org/next-pages-template/assets/20458239/1d38a717-df9e-4ea0-bc10-4bf3ac21a74f)

I wonder is it right or the dependency should be included?

if it should be included, I'm willing to fix this, or should them be declared as peer dependency ?

**Comment by wingkwong** [comment]
Closing - no longer applicable
