### ISSUE TITLE
Broken style 

### ISSUE THREAD

**Issue by isaacdarcilla** [nextui-org/next-pages-template#7]
![image](https://github.com/nextui-org/next-pages-template/assets/22732118/151bc264-c825-4dfb-b6ab-e882cc2ecd9d)

I tried installing this template, I haven't change any of the code. Followed the instructions. How to fix this?

**Comment by GardoTL** [comment]
update ?

**Comment by wingkwong** [comment]
<img width="1427" alt="image" src="https://github.com/nextui-org/next-pages-template/assets/35857179/f8e699e5-689c-4a3b-8543-f8de792aaafe">

Tested with both npm & pnpm and couldn't reproduce the issue.
